import ComposableArchitecture
import SwiftUI

// MARK: - Aria Recap Stories
//
// 6-page story viewer for a single cycle recap. Pages map 1:1 to the
// chapters generated by `CycleRecapGeneration`:
//   0. Theme            (headline + vibe + throughline)
//   1. Body
//   2. Heart & Mind
//   3. Rhythm           (cross-cycle patterns)
//   4. Key Days         (structured highlight reel from KeyDayExtractor)
//   5. What's Coming    (next-cycle preview + Aria CTA)

struct AriaRecapStories: View {
    let store: StoreOf<CycleJourneyFeature>
    @State private var shimmerPhase = false
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    /// One gradient per page. The last one sits in the Aria warm-brown
    /// palette so "What's Coming" reads as the companion's space.
    private let storyGradients: [[Color]] = [
        [DesignColors.recapMenstrualStart, DesignColors.recapMenstrualEnd],
        [DesignColors.recapFollicularStart, DesignColors.recapFollicularEnd],
        [DesignColors.recapOvulatoryStart, DesignColors.recapOvulatoryEnd],
        [DesignColors.recapLutealStart, DesignColors.recapLutealEnd],
        [DesignColors.recapLutealEnd, DesignColors.recapOvulatoryStart],
        [DesignColors.recapAriaStart, DesignColors.recapAriaEnd],
    ]

    var body: some View {
        if let recap = store.recap {
            ZStack {
                LinearGradient(
                    colors: storyGradients[min(recap.currentPage, storyGradients.count - 1)],
                    startPoint: .topLeading,
                    endPoint: .bottomTrailing
                )
                .ignoresSafeArea()
                .animation(.easeInOut(duration: 0.5), value: recap.currentPage)

                VStack(spacing: 0) {
                    VStack(spacing: 14) {
                        storyProgressBars(currentPage: recap.currentPage)

                        HStack {
                            Text(DateFormatter.monthYear.string(from: recap.summary.startDate))
                                .font(.raleway("Medium", size: 13, relativeTo: .caption))
                                .foregroundStyle(.white.opacity(0.7))

                            Spacer()

                            Button { store.send(.recapDismissed) } label: {
                                Image(systemName: "xmark")
                                    .font(.system(size: 14, weight: .bold))
                                    .foregroundStyle(.white.opacity(0.8))
                                    .frame(width: 32, height: 32)
                                    .background(Circle().fill(.white.opacity(0.15)))
                            }
                            .accessibilityLabel("Close recap")
                        }
                    }
                    .padding(.horizontal, 20)
                    .padding(.top, 8)

                    Spacer()

                    if recap.isLoading {
                        storyLoadingContent
                    } else {
                        storyPageContent(recap: recap, page: recap.currentPage)
                            .id(recap.currentPage)
                            .transition(.opacity)
                            .animation(.easeInOut(duration: 0.3), value: recap.currentPage)
                    }

                    Spacer()
                    Spacer()
                }

                VStack(spacing: 0) {
                    Color.clear.frame(height: 70)

                    HStack(spacing: 0) {
                        Color.clear
                            .contentShape(Rectangle())
                            .onTapGesture { goBack(from: recap.currentPage) }
                            .accessibilityLabel("Previous page")
                            .accessibilityAddTraits(.isButton)

                        Color.clear
                            .contentShape(Rectangle())
                            .onTapGesture { goForward(from: recap.currentPage) }
                            .accessibilityLabel("Next page")
                            .accessibilityAddTraits(.isButton)
                    }

                    Color.clear.frame(height: 140)
                }
            }
            .statusBarHidden()
        }
    }

    // MARK: - Progress Bars

    private func storyProgressBars(currentPage: Int) -> some View {
        HStack(spacing: 4) {
            ForEach(0..<RecapState.totalPages, id: \.self) { i in
                Capsule()
                    .fill(i <= currentPage ? Color.white : Color.white.opacity(0.25))
                    .frame(height: 3)
                    .animation(.easeInOut(duration: 0.3), value: currentPage)
            }
        }
    }

    // MARK: - Loading Shimmer

    private var storyLoadingContent: some View {
        VStack(spacing: 24) {
            RoundedRectangle(cornerRadius: 8)
                .fill(Color.white.opacity(shimmerPhase ? 0.2 : 0.08))
                .frame(width: 180, height: 28)

            VStack(spacing: 12) {
                ForEach(0..<3, id: \.self) { i in
                    RoundedRectangle(cornerRadius: 6)
                        .fill(Color.white.opacity(shimmerPhase ? 0.15 : 0.06))
                        .frame(height: 16)
                        .frame(maxWidth: i == 2 ? 200 : .infinity)
                }
            }
            .padding(.horizontal, 40)
        }
        .animation(reduceMotion ? nil : .easeInOut(duration: 1.2).repeatForever(autoreverses: true), value: shimmerPhase)
        .onAppear { if !reduceMotion { shimmerPhase = true } }
    }

    // MARK: - Page Content

    @ViewBuilder
    private func storyPageContent(recap: RecapState, page: Int) -> some View {
        switch page {
        case 0: storyThemePage(recap: recap)
        case 1: storyBodyPage(recap: recap)
        case 2: storyHeartMindPage(recap: recap)
        case 3: storyRhythmPage(recap: recap)
        case 4: storyKeyDaysPage(recap: recap)
        case 5: storyWhatsComingPage(recap: recap)
        default: EmptyView()
        }
    }

    // Ch1 — Theme

    private func storyThemePage(recap: RecapState) -> some View {
        VStack(spacing: 24) {
            Text(recap.cycleVibe.uppercased())
                .font(.raleway("Bold", size: 52, relativeTo: .largeTitle))
                .foregroundStyle(.white.opacity(0.10))
                .tracking(8)

            Text(recap.headline)
                .font(.raleway("Bold", size: 30, relativeTo: .title))
                .foregroundStyle(.white)
                .multilineTextAlignment(.center)

            Text(recap.themeText.cleanedAIText)
                .font(.raleway("Regular", size: 18, relativeTo: .body))
                .foregroundStyle(.white.opacity(0.9))
                .lineSpacing(8)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 32)

            HStack(spacing: 6) {
                Text("Cycle \(recap.summary.cycleNumber)")
                    .font(.raleway("Medium", size: 13, relativeTo: .caption))
                Text("\u{00B7}")
                Text("\(recap.summary.cycleLength) days")
                    .font(.raleway("Medium", size: 13, relativeTo: .caption))
            }
            .foregroundStyle(.white.opacity(0.5))
        }
        .padding(.horizontal, 20)
    }

    // Ch2 — Body

    private func storyBodyPage(recap: RecapState) -> some View {
        VStack(spacing: 28) {
            Image(systemName: "figure.mind.and.body")
                .font(.system(size: 36, weight: .light))
                .foregroundStyle(.white.opacity(0.5))

            Text("Your Body")
                .font(.raleway("Bold", size: 28, relativeTo: .title))
                .foregroundStyle(.white)

            Text(recap.bodyText.cleanedAIText)
                .font(.raleway("Regular", size: 18, relativeTo: .body))
                .foregroundStyle(.white.opacity(0.9))
                .lineSpacing(8)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 32)

            let phaseTotal = recap.summary.phaseBreakdown.menstrualDays
                + recap.summary.phaseBreakdown.follicularDays
                + recap.summary.phaseBreakdown.ovulatoryDays
                + recap.summary.phaseBreakdown.lutealDays
            if phaseTotal > 0 {
                storyPhaseMiniBar(recap: recap)
            }
        }
        .padding(.horizontal, 20)
    }

    // Ch3 — Heart & Mind

    private func storyHeartMindPage(recap: RecapState) -> some View {
        VStack(spacing: 28) {
            Image(systemName: "heart.circle")
                .font(.system(size: 36, weight: .light))
                .foregroundStyle(.white.opacity(0.5))

            Text("Heart & Mind")
                .font(.raleway("Bold", size: 28, relativeTo: .title))
                .foregroundStyle(.white)

            Text(recap.heartMindText.cleanedAIText)
                .font(.raleway("Regular", size: 18, relativeTo: .body))
                .foregroundStyle(.white.opacity(0.9))
                .lineSpacing(8)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 32)

            if let mood = recap.summary.avgMood, let energy = recap.summary.avgEnergy {
                HStack(spacing: 24) {
                    storyMoodIndicator(label: "Mood", value: mood)
                    storyMoodIndicator(label: "Energy", value: energy)
                }
            }
        }
        .padding(.horizontal, 20)
    }

    // Ch4 — Rhythm

    private func storyRhythmPage(recap: RecapState) -> some View {
        VStack(spacing: 28) {
            Image(systemName: "waveform.path")
                .font(.system(size: 36, weight: .light))
                .foregroundStyle(.white.opacity(0.5))

            Text("Your Rhythm")
                .font(.raleway("Bold", size: 28, relativeTo: .title))
                .foregroundStyle(.white)

            Text(recap.rhythmText.cleanedAIText)
                .font(.raleway("Regular", size: 18, relativeTo: .body))
                .foregroundStyle(.white.opacity(0.9))
                .lineSpacing(8)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 32)

            if let label = recap.summary.accuracyLabel {
                HStack(spacing: 8) {
                    Image(systemName: "target")
                        .font(.system(size: 14))
                    Text("Prediction: \(label)")
                        .font(.raleway("Medium", size: 14, relativeTo: .subheadline))
                }
                .foregroundStyle(.white.opacity(0.6))
                .padding(.horizontal, 16)
                .padding(.vertical, 10)
                .background(Capsule().fill(.white.opacity(0.12)))
            }
        }
        .padding(.horizontal, 20)
    }

    // Ch5 — Key Days

    private func storyKeyDaysPage(recap: RecapState) -> some View {
        VStack(spacing: 22) {
            Image(systemName: "sparkle")
                .font(.system(size: 30, weight: .light))
                .foregroundStyle(.white.opacity(0.5))

            Text("Key Days")
                .font(.raleway("Bold", size: 28, relativeTo: .title))
                .foregroundStyle(.white)

            if recap.keyDays.isEmpty {
                Text("No stand-out days this cycle — track your moods and moments next cycle and the story grows richer.")
                    .font(.raleway("Regular", size: 16, relativeTo: .body))
                    .foregroundStyle(.white.opacity(0.8))
                    .multilineTextAlignment(.center)
                    .lineSpacing(6)
                    .padding(.horizontal, 36)
            } else {
                VStack(spacing: 14) {
                    ForEach(recap.keyDays) { keyDay in
                        keyDayRow(keyDay)
                    }
                }
                .padding(.horizontal, 20)
            }
        }
    }

    private func keyDayRow(_ keyDay: KeyDay) -> some View {
        HStack(alignment: .top, spacing: 14) {
            VStack(spacing: 2) {
                Text("DAY")
                    .font(.raleway("SemiBold", size: 10, relativeTo: .caption2))
                    .tracking(0.8)
                    .foregroundStyle(.white.opacity(0.55))
                Text("\(keyDay.day)")
                    .font(.raleway("Black", size: 28, relativeTo: .title2))
                    .foregroundStyle(.white)
            }
            .frame(width: 56)
            .padding(.vertical, 8)
            .background(
                RoundedRectangle(cornerRadius: 12, style: .continuous)
                    .fill(.white.opacity(0.12))
            )

            VStack(alignment: .leading, spacing: 6) {
                HStack(spacing: 6) {
                    Text(keyDay.phase.displayName.uppercased())
                        .font(.raleway("SemiBold", size: 10, relativeTo: .caption2))
                        .tracking(0.8)
                        .foregroundStyle(.white.opacity(0.7))
                    if let hbi = keyDay.hbi {
                        Text("\u{00B7}")
                            .foregroundStyle(.white.opacity(0.4))
                        Text("\(hbi)%")
                            .font(.raleway("SemiBold", size: 11, relativeTo: .caption))
                            .foregroundStyle(.white.opacity(0.7))
                    }
                }
                Text(keyDay.narrative)
                    .font(.raleway("Medium", size: 14, relativeTo: .body))
                    .foregroundStyle(.white.opacity(0.95))
                    .lineSpacing(4)
                    .fixedSize(horizontal: false, vertical: true)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(12)
        .background(
            RoundedRectangle(cornerRadius: 16, style: .continuous)
                .fill(.white.opacity(0.08))
        )
        .overlay(
            RoundedRectangle(cornerRadius: 16, style: .continuous)
                .strokeBorder(.white.opacity(0.14), lineWidth: 1)
        )
    }

    // Ch6 — What's Coming + Aria CTA

    private func storyWhatsComingPage(recap: RecapState) -> some View {
        VStack(spacing: 28) {
            ZStack {
                Circle()
                    .fill(
                        LinearGradient(
                            colors: [
                                DesignColors.ariaBadgeStart,
                                DesignColors.ariaBadgeEnd,
                            ],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )
                    .frame(width: 64, height: 64)

                Text("A")
                    .font(.raleway("Bold", size: 28, relativeTo: .title))
                    .foregroundStyle(.white)
            }

            Text("What's Coming")
                .font(.raleway("Bold", size: 28, relativeTo: .title))
                .foregroundStyle(.white)

            Text(recap.whatsComingText.cleanedAIText)
                .font(.raleway("Regular", size: 17, relativeTo: .body))
                .foregroundStyle(.white.opacity(0.9))
                .lineSpacing(6)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 32)

            Button {
                store.send(.askAriaAboutCycle(recap.summary))
            } label: {
                HStack(spacing: 10) {
                    Text("Talk about this cycle")
                        .font(.raleway("SemiBold", size: 17, relativeTo: .headline))
                    Image(systemName: "arrow.right")
                        .font(.system(size: 14, weight: .semibold))
                }
                .foregroundStyle(DesignColors.recapCTAText)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 18)
                .background(Capsule().fill(.white))
            }
            .padding(.horizontal, 40)
        }
        .padding(.horizontal, 20)
    }

    // MARK: - Helpers

    private func storyPhaseMiniBar(recap: RecapState) -> some View {
        let bd = recap.summary.phaseBreakdown
        let total = bd.menstrualDays + bd.follicularDays + bd.ovulatoryDays + bd.lutealDays
        let phases: [(String, Int, Color)] = [
            ("M", bd.menstrualDays, CyclePhase.menstrual.orbitColor),
            ("F", bd.follicularDays, CyclePhase.follicular.orbitColor),
            ("O", bd.ovulatoryDays, CyclePhase.ovulatory.orbitColor),
            ("L", bd.lutealDays, CyclePhase.luteal.orbitColor),
        ]

        return VStack(spacing: 8) {
            GeometryReader { geo in
                HStack(spacing: 2) {
                    ForEach(Array(phases.enumerated()), id: \.offset) { _, phase in
                        let pct = total > 0 ? CGFloat(phase.1) / CGFloat(total) : 0.25
                        RoundedRectangle(cornerRadius: 3)
                            .fill(phase.2.opacity(0.8))
                            .frame(width: max(4, (geo.size.width - 6) * pct))
                    }
                }
            }
            .frame(height: 6)
            .padding(.horizontal, 60)

            HStack(spacing: 16) {
                ForEach(Array(phases.enumerated()), id: \.offset) { _, phase in
                    HStack(spacing: 4) {
                        Circle().fill(phase.2.opacity(0.8)).frame(width: 6, height: 6)
                        Text("\(phase.1)d")
                            .font(.raleway("Regular", size: 11, relativeTo: .caption2))
                            .foregroundStyle(.white.opacity(0.6))
                    }
                }
            }
        }
    }

    private func storyMoodIndicator(label: String, value: Double) -> some View {
        VStack(spacing: 6) {
            Text(String(format: "%.1f", value))
                .font(.raleway("Bold", size: 24, relativeTo: .title))
                .foregroundStyle(.white)
            Text(label)
                .font(.raleway("Medium", size: 12, relativeTo: .caption))
                .foregroundStyle(.white.opacity(0.6))
        }
        .frame(width: 80)
        .padding(.vertical, 14)
        .background(
            RoundedRectangle(cornerRadius: 16, style: .continuous)
                .fill(.white.opacity(0.12))
        )
    }

    // MARK: - Navigation

    private func goBack(from page: Int) {
        guard page > 0 else { return }
        store.send(.recapPageChanged(page - 1))
    }

    private func goForward(from page: Int) {
        guard page < RecapState.totalPages - 1 else { return }
        store.send(.recapPageChanged(page + 1))
    }
}
